name: Build and Push Docker Image to Docker Hub and Github Packages

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
      - develop

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and Github Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set IMAGE_NAME env variable
        run: echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        shell: bash

      - name: Check out the repo
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to the Github Packages (Container registry)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  redeploy-dev:
    name: Redeploy webhook call to dev
    environment: development
    runs-on: ubuntu-latest
    needs: [push_to_registry]
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Set REPO_NAME env variable
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        shell: bash

      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          headers: '{"X-Token": "${{ secrets.DEPLOY_WEBHOOK_TOKEN }}"}'
          body: >-
            {
              "event": "deployment",
              "repository": "${{ env.REPO_NAME }}",
              "image": "cbna/${{ env.REPO_NAME }}:develop"
            }

  redeploy-prod:
    name: Redeploy webhook call to prod
    environment: production
    runs-on: ubuntu-latest
    needs: [push_to_registry]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set REPO_NAME env variable
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
        shell: bash

      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
          headers: '{"X-Token": "${{ secrets.DEPLOY_WEBHOOK_TOKEN }}"}'
          body: >-
            {
              "event": "deployment",
              "repository": "${{ env.REPO_NAME }}",
              "image": "cbna/${{ env.REPO_NAME }}:latest"
            }
